{{- if .Values.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    {{- include "docker-node-app.labels" . | nindent 4 }}
  name: {{ include "docker-node-app.fullname" . }}
spec:
  selector:
    matchLabels:
      {{- include "docker-node-app.selectorLabels" . | nindent 6 }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
{{- end }}
