#!/bin/bash

PACKAGE_VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g')
docker build -t $IMAGE_NAME:$PACKAGE_VERSION --build-arg MICROSCANNER_TOKEN=$MICROSCANNER_TOKEN .