#!/bin/bash

PACKAGE_VERSION=$(grep version package.json | awk -F \" '{print $4}')
docker build -t $IMAGE_NAME --build-arg MICROSCANNER_TOKEN=$MICROSCANNER_TOKEN .
if [ $DOCKER_TAG == "latest" ]
then
    docker tag $IMAGE_NAME $DOCKER_REPO:$PACKAGE_VERSION
    docker push $DOCKER_REPO:$PACKAGE_VERSION
fi