apiVersion: v1
kind: Service
metadata:
  name: {{ include "docker-node-app.fullname" . }}
  labels:
{{ include "docker-node-app.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "docker-node-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}