name: CI to DockerHub

on:
  push:
    branches: 
      - master
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2
        
      - name: Set Image Name and Version
        id: prep
        run: |
            echo "::set-output name=DOCKER_IMAGE::${{ github.repository }}"
            echo "::set-output name=VERSION::$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')"

      - name: Set Image Tags
        id: tag
        run: |
            if [[ ${{ steps.prep.outputs.VERSION }} =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
              TAGS="${{ steps.prep.outputs.DOCKER_IMAGE }}:${{ steps.prep.outputs.VERSION }},${{ steps.prep.outputs.DOCKER_IMAGE }}:latest"
            else
              TAGS="${{ steps.prep.outputs.DOCKER_IMAGE }}:latest"
            fi
            echo "::set-output name=tags::${TAGS}"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
          
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build & Push Base Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ steps.tag.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.prep.outputs.VERSION }}
          release_name: Docker Release v${{ steps.prep.outputs.VERSION }}
          body: |
            The latest version(s) can be launched with:
              - `docker run -d -p 8080:8080 --name docker-node-app jonfairbanks/docker-node-app:${{ steps.prep.outputs.VERSION }} --restart=always`
          draft: false
          prerelease: false